language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo clean
  - cargo build
  - cargo test --no-default-features --features runtime-tokio
  - cargo test --no-default-features --features runtime-async-std
  - cargo clippy -- -D warnings
  - cargo fmt --all -- --check

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # upload report to codecov
    cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
