name: Auto Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Auto Build CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dependencies
        run: sudo apt-get install libssl-dev

      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Cargo Test For tokio
        uses: actions-rs/cargo@v1
        with:
          command: test --no-default-features --features runtime-tokio

      - name: Cargo Test For async-std
        uses: actions-rs/cargo@v1
        with:
          command: test --no-default-features --features runtime-async-std

      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy -- -D warnings

      - name: Cargo Fmt Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt --all -- --check